// <auto-generated />
using System;
using FancyStore.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FancyStore.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FancyStore.API.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AddressId"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Landmark")
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("FancyStore.API.Models.Banner", b =>
                {
                    b.Property<int>("BannerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BannerId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BannerId");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("FancyStore.API.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CartId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<bool>("SavedForLater")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("CartId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("FancyStore.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Bangles",
                            CreatedAt = new DateTime(2026, 6, 23, 6, 26, 39, 376, DateTimeKind.Utc).AddTicks(1457),
                            ImageUrl = "/images/categories/bangles.jpg",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Dollar Chains",
                            CreatedAt = new DateTime(2026, 6, 23, 6, 26, 39, 376, DateTimeKind.Utc).AddTicks(3094),
                            ImageUrl = "/images/categories/dollar-chains.jpg",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Invisible Chains",
                            CreatedAt = new DateTime(2026, 6, 23, 6, 26, 39, 376, DateTimeKind.Utc).AddTicks(3098),
                            ImageUrl = "/images/categories/invisible-chains.jpg",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Earrings",
                            CreatedAt = new DateTime(2026, 6, 23, 6, 26, 39, 376, DateTimeKind.Utc).AddTicks(3099),
                            ImageUrl = "/images/categories/earrings.jpg",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Hair Accessories",
                            CreatedAt = new DateTime(2026, 6, 23, 6, 26, 39, 376, DateTimeKind.Utc).AddTicks(3101),
                            ImageUrl = "/images/categories/hair-accessories.jpg",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Fancy Items",
                            CreatedAt = new DateTime(2026, 6, 23, 6, 26, 39, 376, DateTimeKind.Utc).AddTicks(3102),
                            ImageUrl = "/images/categories/fancy-items.jpg",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Gift Items",
                            CreatedAt = new DateTime(2026, 6, 23, 6, 26, 39, 376, DateTimeKind.Utc).AddTicks(3103),
                            ImageUrl = "/images/categories/gift-items.jpg",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("FancyStore.API.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CouponId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinOrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("integer");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = 1,
                            Code = "WELCOME10",
                            CreatedAt = new DateTime(2026, 6, 23, 6, 26, 39, 843, DateTimeKind.Utc).AddTicks(1261),
                            DiscountPercent = 10m,
                            IsActive = true,
                            MaxDiscount = 100m,
                            MinOrderAmount = 200m,
                            UsageLimit = 1000,
                            UsedCount = 0,
                            ValidUntil = new DateTime(2027, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CouponId = 2,
                            Code = "FANCY20",
                            CreatedAt = new DateTime(2026, 6, 23, 6, 26, 39, 843, DateTimeKind.Utc).AddTicks(5306),
                            DiscountPercent = 20m,
                            IsActive = true,
                            MaxDiscount = 200m,
                            MinOrderAmount = 500m,
                            UsageLimit = 500,
                            UsedCount = 0,
                            ValidUntil = new DateTime(2027, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FancyStore.API.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<string>("CouponCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DeliveryCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GstAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazorpayOrderId")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.HasIndex("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FancyStore.API.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderItemId"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FancyStore.API.Models.PriceRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PriceRanges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Under ₹500",
                            MaxPrice = 499m,
                            MinPrice = 0m,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Label = "₹500 - ₹1000",
                            MaxPrice = 1000m,
                            MinPrice = 500m,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Label = "₹1000 - ₹2000",
                            MaxPrice = 2000m,
                            MinPrice = 1000m,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Label = "Over ₹2000",
                            MinPrice = 2001m,
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("FancyStore.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNewArrival")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrending")
                        .HasColumnType("boolean");

                    b.Property<string>("Material")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium gold-plated bangles with intricate craftsmanship.",
                            Discount = 10m,
                            ImageUrl = "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&auto=format&fit=crop",
                            IsActive = true,
                            IsBestSeller = false,
                            IsNewArrival = false,
                            IsTrending = false,
                            Name = "Elegant Bridal Bangles Set",
                            Price = 1299m,
                            Stock = 50
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Minimalist and modern invisible chain for daily wear.",
                            Discount = 20m,
                            ImageUrl = "https://images.unsplash.com/photo-1599643478514-4a888f6188dc?w=800&auto=format&fit=crop",
                            IsActive = true,
                            IsBestSeller = false,
                            IsNewArrival = false,
                            IsTrending = false,
                            Name = "Premium Invisible Chain",
                            Price = 499m,
                            Stock = 100
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Trending Korean style elegant drop earrings.",
                            Discount = 0m,
                            ImageUrl = "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&auto=format&fit=crop",
                            IsActive = true,
                            IsBestSeller = false,
                            IsNewArrival = false,
                            IsTrending = false,
                            Name = "Korean Drop Earrings",
                            Price = 299m,
                            Stock = 200
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thick, luxurious dollar chain design.",
                            Discount = 15m,
                            ImageUrl = "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=800&auto=format&fit=crop",
                            IsActive = true,
                            IsBestSeller = false,
                            IsNewArrival = false,
                            IsTrending = false,
                            Name = "Gold Plated Dollar Chain",
                            Price = 899m,
                            Stock = 30
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Traditional bangles embedded with premium artificial rubies.",
                            Discount = 5m,
                            ImageUrl = "https://images.unsplash.com/photo-1629224316810-9d8805b95e76?w=800&auto=format&fit=crop",
                            IsActive = true,
                            IsBestSeller = false,
                            IsNewArrival = false,
                            IsTrending = false,
                            Name = "Ruby Studded Bangles",
                            Price = 1599m,
                            Stock = 20
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stunning hoop earrings with delicate diamond accents.",
                            Discount = 10m,
                            ImageUrl = "https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&auto=format&fit=crop",
                            IsActive = true,
                            IsBestSeller = false,
                            IsNewArrival = false,
                            IsTrending = false,
                            Name = "Diamond Accent Hoops",
                            Price = 599m,
                            Stock = 80
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Timeless pearl necklace perfect for evening wear.",
                            Discount = 25m,
                            ImageUrl = "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=800&auto=format&fit=crop",
                            IsActive = true,
                            IsBestSeller = false,
                            IsNewArrival = false,
                            IsTrending = false,
                            Name = "Classic Pearl Necklace",
                            Price = 1899m,
                            Stock = 15
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sparkling crystal hair accessories for bridal and party wear.",
                            Discount = 0m,
                            ImageUrl = "https://images.unsplash.com/photo-1569397288884-4d43e667d264?w=800&auto=format&fit=crop",
                            IsActive = true,
                            IsBestSeller = false,
                            IsNewArrival = false,
                            IsTrending = false,
                            Name = "Crystal Hair Pin Set",
                            Price = 349m,
                            Stock = 150
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Modern rose gold cuff with a sleek, minimalist aesthetic.",
                            Discount = 20m,
                            ImageUrl = "https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=800&auto=format&fit=crop",
                            IsActive = true,
                            IsBestSeller = false,
                            IsNewArrival = false,
                            IsTrending = false,
                            Name = "Rose Gold Cuff Bangle",
                            Price = 899m,
                            Stock = 45
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elegant teardrop earrings featuring deep blue sapphire replicas.",
                            Discount = 15m,
                            ImageUrl = "https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=800&auto=format&fit=crop",
                            IsActive = true,
                            IsBestSeller = false,
                            IsNewArrival = false,
                            IsTrending = false,
                            Name = "Sapphire Tear Drop Earrings",
                            Price = 649m,
                            Stock = 60
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fashion-forward multi-layered gold chain.",
                            Discount = 30m,
                            ImageUrl = "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&auto=format&fit=crop",
                            IsActive = true,
                            IsBestSeller = false,
                            IsNewArrival = false,
                            IsTrending = false,
                            Name = "Layered Gold Chain",
                            Price = 1199m,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Perfect gift item for storing precious jewelry securely.",
                            Discount = 0m,
                            ImageUrl = "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop",
                            IsActive = true,
                            IsBestSeller = false,
                            IsNewArrival = false,
                            IsTrending = false,
                            Name = "Premium Velvet Jewelry Box",
                            Price = 1299m,
                            Stock = 40
                        });
                });

            modelBuilder.Entity("FancyStore.API.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ReviewId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("FancyStore.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@gmail.com",
                            IsBlocked = false,
                            Mobile = "9999999999",
                            Name = "Fancy Store Admin",
                            PasswordHash = "$2a$11$32.YDLemy2B2Qcwor8b.Mu2Q6mqAyEU9QZnB0wYhUj1JVZfquPt2a",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("FancyStore.API.Models.Wishlist", b =>
                {
                    b.Property<int>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WishlistId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("WishlistId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("FancyStore.API.Models.Address", b =>
                {
                    b.HasOne("FancyStore.API.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FancyStore.API.Models.Cart", b =>
                {
                    b.HasOne("FancyStore.API.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FancyStore.API.Models.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FancyStore.API.Models.Order", b =>
                {
                    b.HasOne("FancyStore.API.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FancyStore.API.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FancyStore.API.Models.OrderItem", b =>
                {
                    b.HasOne("FancyStore.API.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FancyStore.API.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FancyStore.API.Models.Product", b =>
                {
                    b.HasOne("FancyStore.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FancyStore.API.Models.Review", b =>
                {
                    b.HasOne("FancyStore.API.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FancyStore.API.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FancyStore.API.Models.Wishlist", b =>
                {
                    b.HasOne("FancyStore.API.Models.Product", "Product")
                        .WithMany("Wishlists")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FancyStore.API.Models.User", "User")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FancyStore.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("FancyStore.API.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("FancyStore.API.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("FancyStore.API.Models.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("CartItems");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlists");
                });
#pragma warning restore 612, 618
        }
    }
}
